module.exports = {
  en: {
    skipContent: "Skip to content",
    navigation: "Workflow navigation",
    contents: "On this page",
    openContents: "Contents",
    search: "Search",
    closeImage: "Close image",
    imageViewer: "Image preview",
    supportDetails: "Environment and verification",
    osSelector: "Choose an operating system",
    osPending: "Coming later",
    osSelectorNote: "Windows instructions are available. macOS and Linux procedures will be written and verified later.",
    needsReview: "Needs review",
    verified: "Verified",
    feedback: "Questions and feedback",
    menu: "Menu",
    breadcrumb: "Breadcrumb",
    previous: "Previous",
    next: "Next",
    outcome: "Outcome",
    prerequisites: "Before you start",
    commonProblems: "Common problems",
    completion: "Completion check",
    verification: "Verification state",
    verificationStatus: "Status",
    verificationEnvironment: "Environment",
    verificationWorkflow: "Workflow",
    verificationDate: "Last verified",
    verificationSupport: "Operating-system support",
    latestUpdate: "Latest update:",
    support: "Support"
  },
  ko: {
    skipContent: "본문으로 이동",
    navigation: "작업 단계",
    contents: "이 페이지에서",
    openContents: "목차",
    search: "검색",
    closeImage: "이미지 닫기",
    imageViewer: "이미지 미리보기",
    supportDetails: "지원 환경 및 검증",
    osSelector: "운영체제 선택",
    osPending: "준비 중",
    osSelectorNote: "현재 Windows 안내를 제공합니다. macOS와 Linux 절차는 추후 작성·검증할 예정입니다.",
    needsReview: "재검증 필요",
    verified: "검증 완료",
    feedback: "질문과 피드백",
    menu: "메뉴",
    breadcrumb: "경로",
    previous: "이전",
    next: "다음",
    outcome: "완료할 작업",
    prerequisites: "시작 전 확인",
    commonProblems: "자주 발생하는 문제",
    completion: "완료 확인",
    verification: "검증 상태",
    verificationStatus: "상태",
    verificationEnvironment: "환경",
    verificationWorkflow: "검증 대상",
    verificationDate: "마지막 검증",
    verificationSupport: "운영체제 지원",
    latestUpdate: "최근 업데이트:",
    support: "후원"
  }
};
